# Generated by Django 5.1.4 on 2024-12-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('One Bed', 'One Bed'), ('Two Beds', 'Two Beds')], max_length=10)),
                ('availability_status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Needs clean', 'Needs clean'), ('Needs verify', 'Needs verify')], max_length=20)),
            ],
        ),
    ]
