# Generated by Django 5.1.4 on 2025-01-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(choices=[('Government Officer', 'Government Officer'), ('Self-Government Officer', 'Self-Government Officer'), ('Private Sector Employee', 'Private Sector Employee')], default='Government Officer', max_length=30)),
                ('nid', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('total_person', models.IntegerField(blank=True, null=True)),
                ('motive_of_visiting', models.TextField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_rental_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('One King Size Bed', 'One King Size Bed'), ('Two King Size Beds', 'Two King Size Beds')], max_length=40)),
                ('room_category', models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], default='Regular', max_length=10)),
                ('availability_status', models.CharField(choices=[('Vacant', 'Vacant'), ('Booked', 'Booked'), ('Occupied', 'Occupied'), ('Needs Housekeeping', 'Needs Housekeeping'), ('Needs verify', 'Needs verify'), ('Locked', 'Locked')], default='Vacant', max_length=20)),
                ('building', models.CharField(choices=[('New Building', 'New Building'), ('Old Building', 'Old Building')], default='New Building', max_length=20)),
                ('floor', models.CharField(choices=[('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor')], default='First Floor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rental_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_food_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_other_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Government Officer', 'Government Officer'), ('Self-Government Officer', 'Self-Government Officer'), ('Private Sector Employee', 'Private Sector Employee')], max_length=30)),
                ('room_type', models.CharField(choices=[('One Bed', 'One Bed'), ('Two Beds', 'Two Beds')], max_length=10)),
                ('days_range', models.CharField(blank=True, help_text='e.g., 1-3, 4-7, or 7+', max_length=10, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('user_type', 'room_type', 'days_range')},
            },
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.room')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.room'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_menu', models.TextField()),
                ('Order_time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.room')),
            ],
        ),
    ]
