# Generated by Django 5.1.4 on 2024-12-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='phone',
        ),
    ]
