# Generated by Django 5.1.4 on 2024-12-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('motive_of_visiting', models.TextField(blank=True, null=True)),
                ('total_person', models.IntegerField()),
                ('total_days', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_rental_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('Government Officer', 'Government Officer'), ('Self-Government Officer', 'Self-Government Officer'), ('Private Sector Employee', 'Private Sector Employee')], default='Government Officer', max_length=30)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.room')),
            ],
        ),
    ]
