# Generated by Django 5.1.4 on 2024-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_guest_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
