# Generated by Django 5.1.4 on 2024-12-10 06:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_room_room_description_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Needs clean', 'Needs clean'), ('Needs verify', 'Needs verify'), ('Locked', 'Locked')], max_length=20),
        ),
        migrations.CreateModel(
            name='CheckoutSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rental_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_food_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_other_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_menu', models.TextField()),
                ('Order_time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Launch', 'Launch'), ('Dinner', 'Dinner')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.guest')),
            ],
        ),
    ]
