# Generated by Django 5.1.4 on 2024-12-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_guest_check_in_date_guest_check_out_date_guest_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_description',
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(choices=[('New Building', 'New Building'), ('Old Building', 'Old Building')], default='New Building', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor')], default='First Floor', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], default='Regular', max_length=10),
        ),
    ]
