# Generated by Django 5.1.4 on 2024-12-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_room_availability_status_checkoutsummary_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercost',
            old_name='item',
            new_name='items',
        ),
    ]
