# Generated by Django 5.1.4 on 2024-12-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_othercost_cost_remove_othercost_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Booked', 'Booked'), ('Occupied', 'Occupied'), ('Needs clean', 'Needs clean'), ('Needs verify', 'Needs verify'), ('Locked', 'Locked')], max_length=20),
        ),
    ]
