# Generated by Django 5.1.4 on 2024-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_othercost_cost_remove_othercost_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Order_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20),
        ),
    ]
