# Generated by Django 5.1.4 on 2024-12-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_item_othercost_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='signature',
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Government Officer', 'Government Officer'), ('Self-Government Officer', 'Self-Government Officer'), ('Private Sector Employee', 'Private Sector Employee')], max_length=30)),
                ('room_type', models.CharField(choices=[('One Bed', 'One Bed'), ('Two Beds', 'Two Beds')], max_length=10)),
                ('days_range', models.CharField(help_text='e.g., 1-3, 4-7, or 8+', max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('user_type', 'room_type', 'days_range')},
            },
        ),
    ]
