# Generated by Django 5.1.4 on 2024-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_room_room_description_room_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Booked', 'Booked'), ('Occupied', 'Occupied'), ('Needs clean', 'Needs clean'), ('Needs verify', 'Needs verify'), ('Locked', 'Locked')], default='Vacant', max_length=20),
        ),
    ]
