# Generated by Django 5.1.4 on 2024-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_food_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='total_food_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='total_other_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
