# Generated by Django 5.1.4 on 2025-01-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_room_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='total_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
