# Generated by Django 5.1.4 on 2024-12-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_guest_designation_alter_guest_name_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='days_range',
            field=models.CharField(blank=True, help_text='e.g., 1-3, 4-7, or 7+', max_length=10, null=True),
        ),
    ]
