# Generated by Django 5.1.4 on 2024-12-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_room_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
