# Generated by Django 5.1.4 on 2024-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonourBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('photo', models.ImageField(upload_to='img/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('designation_type', models.CharField(choices=[('DC', 'DC'), ('NDC', 'NDC')], default='DC', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='img/')),
                ('designation', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
