# Generated by Django 5.1.4 on 2024-12-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honourboard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
