# Generated by Django 5.1.4 on 2024-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_honourboard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honourboard',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
