# Generated by Django 5.1.4 on 2024-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('NDC', 'NDC'), ('Assistant Accountant', 'Assistant Accountant')], default='Assistant Accountant', max_length=40, null=True),
        ),
    ]
